export const countriesData = [
  {
    country: "India",
    states: [
      {
        state: "Uttarakhand",
        cities: [
          "Dehradun",
          "Haridwar",
          "Rishikesh",
          "Nainital",
          "Mussoorie",
          "Almora",
          "Rudrapur",
          "Haldwani",
          "Kashipur",
          "Tehri",
          "Pauri",
          "Roorkee",
          "Chamoli",
          "Pithoragarh",
          "Udham Singh Nagar",
          "Champawat",
          "Bageshwar",
          "Ranikhet",
          "Badrinath",
          "Kedarnath",
          "Gopeshwar",
          "Jageshwar",
        ],
      },
      {
        state: "Rajasthan",
        cities: [
          "Jaipur",
          "Jodhpur",
          "Udaipur",
          "Ajmer",
          "Kota",
          "Bikaner",
          "Alwar",
          "Sikar",
          "Mount Abu",
          "Jaisalmer",
          "Chittorgarh",
          "Barmer",
          "Bharatpur",
          "Sawai Madhopur",
          "Tonk",
          "Bhilwara",
          "Pali",
          "Hanumangarh",
        ],
      },
      {
        state: "Tamil-Nadu",
        cities: [
          "Chennai",
          "Coimbatore",
          "Madurai",
          "Tiruchirappalli",
          "Salem",
          "Tirunelveli",
          "Tiruppur",
          "Vellore",
          "Erode",
          "Thoothukudi",
          "Nagercoil",
          "Thanjavur",
          "Dindigul",
          "Cuddalore",
          "Kanchipuram",
          "Tiruvannamalai",
          "Karur",
        ],
      },
      {
        state: "Punjab",
        cities: [
          "Amritsar",
          "Ludhiana",
          "Jalandhar",
          "Patiala",
          "Bathinda",
          "S.A.S. Nagar",
          "Hoshiarpur",
          "Moga",
          "Pathankot",
          "Batala",
          "Abohar",
          "Sangrur",
          "Firozpur",
          "Faridkot",
          "Rupnagar",
          "Mansa",
          "Fatehgarh Sahib",
        ],
      },
    ],
  },
  {
    country: "United States",
    states: [
      {
        state: "California",
        cities: [
            "Los Angeles",
            "San Francisco",
            "San Diego",
            "San Jose",
            "Sacramento",
            "Oakland",
            "Fresno",
            "Long Beach",
            "Anaheim",
            "Santa Ana",

          ],
      },
      {
        state: "New York",
        cities:  [
            "New York City",
            "Buffalo",
            "Rochester",
            "Syracuse",
            "Albany",
            "Yonkers",
            "White Plains",
            "New Rochelle",
            "Mount Vernon",
            "Schenectady",
          ],
      },
      {
        state: "Taxas",
        cities: [
            "Houston",
            "Dallas",
            "Austin",
            "San Antonio",
            "Fort Worth",
            "El Paso",
            "Arlington",
            "Plano",
            "Lubbock",
            "Corpus Christi",
          ],
      },
    ],
  },
  {
    country: "Russia",
    states: [
      {
        state: "Moscow Oblast",
        cities: [
          "Moscow",
          "Sergiyev Posad",
          "Korolyov",
          "Klin",
          "Balashikha",
          "Mytishchi",
          "Podolsk",
          "Pushkino",
          "Dmitrov",
          "Zelenograd",
        ],
      },
      {
        state: "Saint Petersburg",
        cities: [
          "Saint Petersburg",
          "Gatchina",
          "Vyborg",
          "Kolpino",
          "Kronshtadt",
          "Sosnovy Bor",
          "Luga",
          "Tikhvin",
          "Tosno",
          "Slantsy",
        ],
      },
      {
        state: "Tatarstan",
        cities: [
          "Kazan",
          "Naberezhnye Chelny",
          "Nizhnekamsk",
          "Almetyevsk",
          "Zelenodolsk",
          "Elabuga",
          "Bugulma",
          "Chistopol",
          "Leninogorsk",
          "Zainsk",
        ],
      },
    ],
  },
];
